### ISSUE TITLE
Meet & Discuss - Formatted Text: current state and future?

### ISSUE THREAD

**Issue by travisleithead** [WICG/canvas-formatted-text#13]
Hi folks,

With the recent [explainer updates](https://github.com/WICG/canvas-formatted-text/blob/main/README.md) to the Formatted Text proposal, I'd like to issue a general call to see if interested parties in the WICG might want to get together for a virtual meeting to discuss/review this API in its current shape and raise issues and thoughts?

Right now only the [data model](https://github.com/WICG/canvas-formatted-text/blob/main/explainer-datamodel.md) is fairly decently fleshed out; there's been some thought put into the [rendering](https://github.com/WICG/canvas-formatted-text/blob/main/explainer-rendering.md) of the data model (primarily for Canvas), and almost nothing proposed for the [text metrics ](https://github.com/WICG/canvas-formatted-text/blob/main/explainer-metrics.md)part (which is arguably the most interesting bit). With that in mind, I still see value in hearing folks' thoughts on the direction this is headed and even brainstorming a bit into what comes next. For certain, there are many varied use cases and the recent integration of CSS into the data model (I believe) helps to support many of the text layout and rendering use cases that parties have. This seems like a great moment to stop and listen to the community.

Some folks that might be interested in joining:
@bfgeek @fserb @sushraja-msft @tantek @mysteryDate @hober @cynthia @atanassov @tabatkins @rocallahan @stpeter @gregwhitworth @litherum

I imagine sometime in June would be great--I'm available nearly every week Wed-Fri and can make most times work. I suspect perhaps 1 to 1.5 hours would be a time box.

**Comment by travisleithead** [comment]
Tentatively proposing June 17th, at 1700 UTC. How does that work for folks?

**Comment by sushraja-msft** [comment]
Im in, hope this works for the other folks !

**Comment by travisleithead** [comment]
I've put together the meeting invite and rough agenda, assuming June 17: https://github.com/WICG/canvas-formatted-text/blob/main/meetings/2021-06-17.md

**Comment by fserb** [comment]
the proposed time sgtm.

**Comment by yjbanov** [comment]
I'd like to attend. I may be able to contribute something in the "Additional use cases to consider?" portion from Flutter's perspective.

**Comment by travisleithead** [comment]
Thanks everyone who joined! We had a great discussion and I'm excited to investigate and start designing the metrics stuff.

We should get together again, I will file a new issue to track input on the next meeting.

**Comment by travisleithead** [comment]
Minutes will be posted shortly at: https://github.com/WICG/canvas-formatted-text/blob/main/meetings/2021-06-17.md
