### ISSUE TITLE
Next Meeting of Formatted Text

### ISSUE THREAD

**Issue by travisleithead** [WICG/canvas-formatted-text#14]
After our first successful meeting (#13), there is still lots to discuss and having another meeting on the calendar will be a good forcing function to make progress on the design of the metrics explainer.

Please mark your calendars for August 11, at 1500 UTC (that's 8am Pacific). Meeting page with details [is here](https://github.com/WICG/canvas-formatted-text/blob/main/meetings/2021-08-18.md)

@bfgeek @fserb @sushraja-msft @tantek @mysteryDate @hober @cynthia @atanassov @tabatkins @rocallahan @stpeter @gregwhitworth @litherum @yjbanov @nhelfman

**Comment by travisleithead** [comment]
Things have been a little slower making progress here than I would have liked, plus summer vacation plans, etc., so, I'm adjusting the timeframes of [the Doodle poll](https://doodle.com/poll/wthtnv9ymmae83x9) (and reducing options to simplify). If you haven't already jumped in to mark your availability, please do so! Planning to meet in the morning, Pacific time (1600 UTC).

**Comment by fserb** [comment]
I think we missed this? Do you want to propose another date?

**Comment by travisleithead** [comment]
Indeed. Proposing August 11th @ 1500 UTC based on forward-projecting from prior Doodle poll results. Please comment if you absolutely cannot make that time work.

**Comment by travisleithead** [comment]
Meeting info is at https://github.com/WICG/canvas-formatted-text/blob/main/meetings/2021-08-18.md for this coming Wednesday. Note: I updated the Google Meet link to match another link on private meeting request I received so everything should be lined up. :)

**Comment by travisleithead** [comment]
📢 Our next FormattedText meeting has been delayed by one week due to some scheduling conflicts. New meeting date is 18 Aug 2021 (same time). Please adjust your calendars! Thanks, and sorry about the last minute notice!

**Comment by travisleithead** [comment]
Notes added to the meeting page. Thanks everyone for coming today!
