### ISSUE TITLE
There is a trivial mistake in the `Formatted Text - Input Data Model`

### ISSUE THREAD

**Issue by michael8090** [WICG/canvas-formatted-text#53]
https://github.com/WICG/canvas-formatted-text/blob/main/explainer-datamodel.md#formatted-text---input-data-model

It should be constraints.width - box.marginRightBottom - box.width instead of constraints.width - box.marginRightBottom + box.width when calculating the line constraint.

I've created a PR to fix it.

https://github.com/WICG/canvas-formatted-text/pull/52

**Comment by travisleithead** [comment]
Merged. Thanks a lot!
