### ISSUE TITLE
Use cases for advanced justification and hyphenation features in Canvas Formatted Text?

### ISSUE THREAD

**Issue by travisleithead** [WICG/canvas-formatted-text#7]
Copied from: https://github.com/MicrosoftEdge/MSEdgeExplainers/issues/375

A variety of additional text justification and hyphenation features are available in HTML. Are there important use-cases for including these features?

**Comment by travisleithead** [comment]
Plan to support these properties through CSS `styleMap` on the data model.

**Comment by littledan** [comment]
@LeaVerou asked a related question at https://github.com/tc39/proposal-intl-segmenter/issues/149
